
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-20.04, ubuntu-18.04, ubuntu-20.04, ubuntu-latest, windows-latest]
        platform: [x86, x64]
        compiler: [gnu, clang]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Exotic Libraries And Run Regression
        uses: exoticlibraries/exotic-action@v1.0
        with:
          download-exotic-libraries: false
          run-regression: false
          test-folder-recursive: true
          test-folders: |
            test/
          test-exclude-file-pattern: |
            crash_test.c
            
        
