
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        platform: [x86, x64]
        compiler: [gnu, clang]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Exotic Libraries And Run Regression
        uses: exoticlibraries/exotic-action@v1.0
        with:
          download-exotic-libraries: true
          run-regression: false
          test-folder-recursive: true
          test-folders: |
            test/
          test-exclude-file-pattern: |
            crash_test.c
          compiler-options-for-tests: |
            -I. -I../include -I../../include -I../../../include -I./include
          regression-cli-options: |
            --cester-printversion
            
        
